---
- name: Install Prerequisites
  hosts: your_remote_server
  become: true  # This enables sudo

  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Install apt packages
      apt:
        name: "{{ item }}"
      loop:
        - python3
        - python3-pip

    - name: Install pip packages
      pip:
        name: docker
      become: false  # Don't use sudo for pip

    - name: Display installed packages
      command: "pip list"
      register: installed_packages

    - name: Display installed packages output
      debug:
        var: installed_packages.stdout_lines
