---
- name: Stop and remove old Docker containers
  hosts: your_target_hosts
  become: true  # This enables sudo
  tasks:
    - name: Get list of running containers
      docker_container_info:
        filters:
          status: running
      register: running_containers

    - name: Stop and remove old containers
      docker_container:
        name: "{{ item.Names[0] }}"
        state: stopped
        remove: yes
      loop: "{{ running_containers.containers }}"
      when: item.Image in ["old_image1:tag", "old_image2:tag", "old_image3:tag"]
