# use ansible-vault
# ansible-vaults can be used like "{{your_vault_var}}"
# to use it use --ask-vault-pass

# sudo apt-get install sshpass
# to use ssh password while authentication use --ask-pass
# ssh-keyscan 45.56.127.107 >> ~/.ssh/known_hosts

# use a .ini file to add your host name in my case there is a inventory.ini file 
# to run it sudo ansible-playbook -i inventory.ini update-containers.yaml --ask-vault-pass --ask-pass

---
- name: Pull Docker images from private Docker Hub
  hosts: your_vm_group
  become: yes  # This enables sudo

  tasks:

    - name: Include encrypted passwords
      include_vars:
        file: secrets.yml

    - name: Log in to Docker Hub
      docker_login:
        username: "{{ your_dockerhub_username }}" # This should be a variable from secrets.yaml
        password: "{{ your_dockerhub_password }}" # This should be a variable from secrets.yaml
        registry_url: https://index.docker.io/v1/

    - name: Pull Docker images
      docker_image:
        name: "{{ item.image }}"
        source: pull
      loop:
        - { image: elsyslab/elsyslabs-website:v1.0.1 }
        # Add more images as needed

    - name: Start containers with custom names
      docker_container:
        name: "{{ item.name }}"
        image: "{{ item.image }}"
        state: started
        ports:
            - "3001:3000"
      loop:
        - { name: elsyslabs-website, image: elsyslab/elsyslabs-website:v1.0.1 }
        # Add more containers as needed, my passwords are in secrets.yaml file as key pair values
